app_quizz/src/Entity/Reponse.php
<?php

namespace App\Entity;

use App\Repository\ReponseRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReponseRepository::class)]
class Reponse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'reponses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Question $question = null;

    #[ORM\Column(length: 255)]
    private ?string $reponse = null;

    #[ORM\Column]
    private ?bool $reponse_expected = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): static
    {
        $this->question = $question;

        return $this;
    }

    public function getReponse(): ?string
    {
        return $this->reponse;
    }

    public function setReponse(string $reponse): static
    {
        $this->reponse = $reponse;

        return $this;
    }

    public function isReponseExpected(): ?bool
    {
        return $this->reponse_expected;
    }

    public function setReponseExpected(bool $reponse_expected): static
    {
        $this->reponse_expected = $reponse_expected;

        return $this;
    }
}

app_quizz/src/Form/ReponseType.php
<?php

namespace App\Form;

use App\Entity\Question;
use App\Entity\Reponse;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReponseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('reponse')
            ->add('reponse_expected')
            ->add('question', EntityType::class, [
                'class' => Question::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reponse::class,
        ]);
    }
}

app_quizz/templates/reponse/_delete_form.html.twig
<form method="post" action="{{ path('app_reponse_delete', {'id': reponse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reponse.id) }}">
    <button class="btn">Delete</button>
</form>

app_quizz/templates/reponse/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app_quizz/templates/reponse/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reponse{% endblock %}

{% block body %}
    <h1>Edit Reponse</h1>

    {{ include('reponse/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reponse_index') }}">back to list</a>

    {{ include('reponse/_delete_form.html.twig') }}
{% endblock %}

app_quizz/templates/reponse/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reponse index{% endblock %}

{% block body %}
    <h1>Reponse index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Reponse</th>
                <th>Reponse_expected</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reponse in reponses %}
            <tr>
                <td>{{ reponse.id }}</td>
                <td>{{ reponse.reponse }}</td>
                <td>{{ reponse.reponseExpected ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_reponse_show', {'id': reponse.id}) }}">show</a>
                    <a href="{{ path('app_reponse_edit', {'id': reponse.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_reponse_new') }}">Create new</a>
{% endblock %}

app_quizz/templates/reponse/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reponse{% endblock %}

{% block body %}
    <h1>Create new Reponse</h1>

    {{ include('reponse/_form.html.twig') }}

    <a href="{{ path('app_reponse_index') }}">back to list</a>
{% endblock %}

app_quizz/templates/reponse/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reponse{% endblock %}

{% block body %}
    <h1>Reponse</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reponse.id }}</td>
            </tr>
            <tr>
                <th>Reponse</th>
                <td>{{ reponse.reponse }}</td>
            </tr>
            <tr>
                <th>Reponse_expected</th>
                <td>{{ reponse.reponseExpected ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reponse_index') }}">back to list</a>

    <a href="{{ path('app_reponse_edit', {'id': reponse.id}) }}">edit</a>

    {{ include('reponse/_delete_form.html.twig') }}
{% endblock %}